### ISSUE TITLE
Task in Console not working

### ISSUE THREAD

**Issue by chiarastrambabadiale** [TimDomino/ptsot#1]
I have downloaded pyhton 3.6 and Spyder 3.6 and run the code. However, the task is displayed in the Console IPyhton, without errors, but after Participant ID selection, it is not working and the clock is not interactive.
Any clues to solve this problem?

Many thanks!

**Comment by TimDomino** [comment]
Try running the code directly from the console using `python3 perspective_taking_test.py` and report on your result. I am not familiar with Spyder, but maybe it's not compatible with the interactive functions of matplotlib.
