### ISSUE TITLE
paper link is not working

### ISSUE THREAD

**Issue by JiaLiu000** [TimDomino/ptsot#2]
Hi, I try to get the reference for citation but seems the link of "http://spatiallearning.org/resource-info/Spatial_Ability_Tests/PTSOT.pdf" is not working. Could you please upload the paper for citation again? Thanks.

**Comment by TimDomino** [comment]
Hi there, they seem to have changed the name of the test to "Object Perspective/Spatial Orientation Test". I have adapted the link to the testing materials in the readme file.
